# Generated by Django 4.2.3 on 2023-07-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='recipient',
            new_name='recipient_static_data',
        ),
    ]
