# Generated by Django 4.2.3 on 2023-07-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_initial'),
        ('nota', '0002_rename_recipient_nota_recipient_static_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='recipeient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
            preserve_default=False,
        ),
    ]
